OPENAI_API_KEY = "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"
ELEVENLABS_API_KEY = "sk_54ef6d7ea8cf9bc4a4eaf84313adf66f8b04d6b501deae8a"
