OPENAI_API_KEY = "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"
ELEVENLABS_API_KEY = "sk_54ef6d7ea8cf9bc4a4eaf84313adf66f8b04d6b501deae8a"
